/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegestion;

import idomothings.Actuador;
import idomothings.Seccion;
import idomothings.Sensor;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author cristian
 */
public class Add extends javax.swing.JPanel {
    
    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Climatizacion y Calderas");
        jComboBox1.addItem("Control de toldos y persianas");
        jComboBox1.addItem("Control de luces y paneles");
        jComboBox1.addItem("Control de temperatura");
        jComboBox1.addItem("Detector de Movimiento");
        jComboBox1.addItem("Detector de Incendios");
        jComboBox1.addItem("Acceso a camaras");
        jComboBox1.addItem("Control de Humedad");
        jComboBox1.addItem("Control de alertas");
        jComboBox1.addItem("Control de puertas");
        
    }
    @Override
    
    protected void paintComponent(Graphics g){
   
    super.paintComponent(g);
    g.drawImage(new ImageIcon("src/interfacegestion/casas.jpg").getImage(),0,0 ,1054,700, this);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        btnAdicionar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        jSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {"Cocina", "Alcoba", "Sala", "Comedor", "Patio", "Baño"}));

        btnAdicionar.setText("Add");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionar)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnAdicionar)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        uno.contador_codigo++;
        System.out.println("con"+uno.contador_codigo);
                    String itemSeleccionado = (String)jComboBox1.getSelectedItem();
    switch(itemSeleccionado){
        case "Control de toldos y persianas": 
            uno.Casa.addDispositivo(new Actuador("142-"+uno.contador_codigo, "21sfsf", itemSeleccionado, jSpinner1.getValue().toString(), true));
            break;
        case "Climatizacion y Calderas":
            uno.Casa.addDispositivo(new Actuador("142-"+uno.contador_codigo, "232fdf", itemSeleccionado, jSpinner1.getValue().toString(), true));
            break;
        case "Control de luces y paneles":
            uno.Casa.addDispositivo(new Actuador("142-"+uno.contador_codigo, "hjhj23", itemSeleccionado, jSpinner1.getValue().toString(), true));
            break;
        case "Control de temperatura":
             uno.Casa.addDispositivo(new Sensor("142-"+uno.contador_codigo, "2324dfdf", itemSeleccionado, jSpinner1.getValue().toString(), true));
            break;
        case "Detector de Movimiento":
             uno.Casa.addDispositivo(new Sensor("142-"+uno.contador_codigo, "hkhk12", itemSeleccionado, jSpinner1.getValue().toString(), true));
            break;
        case "Detector de Incendios":
             uno.Casa.addDispositivo(new Sensor("142-"+uno.contador_codigo, "sdsd12", itemSeleccionado, jSpinner1.getValue().toString(), true));
            break;
        case "Acceso a camaras":
            System.out.println("entro al if de accespo"); 
            uno.Casa.addDispositivo(new Actuador("142-"+uno.contador_codigo, "wewe2323", itemSeleccionado, jSpinner1.getValue().toString(), true));
            break;
          case  "Control de Humedad":
               uno.Casa.addDispositivo(new Sensor("142-"+uno.contador_codigo, "1dfdf313", itemSeleccionado, jSpinner1.getValue().toString(), true));
            break;
          case "Control de alertas":
               uno.Casa.addDispositivo(new Actuador("142-"+uno.contador_codigo, "ghgh", itemSeleccionado, jSpinner1.getValue().toString(), true));
            break;
           case   "Control de puertas":
                uno.Casa.addDispositivo(new Actuador("142-"+uno.contador_codigo, "2323sd", itemSeleccionado, jSpinner1.getValue().toString(), true));
            break;
    }
    
         
    }//GEN-LAST:event_btnAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
